# Generated by Django 4.1.9 on 2023-06-12 06:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("basic", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubjectWeTeach",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100)),
                ("image", models.ImageField(blank=True, upload_to="")),
                ("class_duration", models.CharField(max_length=100)),
                ("subject_type", models.CharField(choices=[("half", "half"), ("full", "full")], max_length=20)),
            ],
        ),
    ]
