# Generated by Django 4.1.9 on 2023-06-12 06:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("basic", "0002_subjectweteach"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="subjectweteach",
            options={"verbose_name": "Subject We Teach", "verbose_name_plural": "Subject We Teach"},
        ),
        migrations.AlterField(
            model_name="information",
            name="about_school",
            field=models.TextField(),
        ),
    ]
