# Generated by Django 4.1.9 on 2023-06-12 07:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("basic", "0003_alter_subjectweteach_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="information",
            name="phone_number",
        ),
        migrations.AddField(
            model_name="information",
            name="phone_number",
            field=models.ManyToManyField(to="basic.phonenumber"),
        ),
    ]
