# Generated by Django 4.1.9 on 2023-06-12 07:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("basic", "0004_remove_information_phone_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="information",
            name="our_experience",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
