# Generated by Django 4.1.9 on 2023-06-12 07:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("basic", "0005_information_our_experience"),
    ]

    operations = [
        migrations.AddField(
            model_name="information",
            name="about_image",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
