# Generated by Django 4.1.9 on 2023-06-12 08:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("basic", "0006_information_about_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="description",
            field=models.TextField(),
        ),
    ]
