# Generated by Django 4.1.9 on 2023-06-12 08:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("basic", "0007_alter_news_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="information",
            name="facebook_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="information",
            name="instagram_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="information",
            name="school_logo",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
        migrations.AddField(
            model_name="information",
            name="tiktok_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="information",
            name="youtube_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
