# Generated by Django 4.1.9 on 2023-06-12 09:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("basic", "0008_information_facebook_url_information_instagram_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="information",
            name="info_video",
            field=models.URLField(blank=True, null=True),
        ),
    ]
