# Generated by Django 4.1.9 on 2023-06-12 11:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("basic", "0009_information_info_video"),
    ]

    operations = [
        migrations.AddField(
            model_name="subjectweteach",
            name="description",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
