# Generated by Django 4.1.9 on 2023-06-12 11:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("basic", "0010_subjectweteach_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="events",
            name="description",
            field=models.TextField(),
        ),
    ]
