# Generated by Django 4.1.9 on 2023-06-12 11:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("basic", "0011_alter_events_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="news",
            name="created_by",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="news",
            name="created_date",
            field=models.DateField(auto_now_add=True),
        ),
    ]
