# Generated by Django 4.1.9 on 2023-06-12 11:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("basic", "0012_news_created_by_alter_news_created_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="map",
            field=models.URLField(blank=True, null=True),
        ),
    ]
