# Generated by Django 4.1.9 on 2023-06-12 11:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("basic", "0014_remove_contact_map_information_map"),
    ]

    operations = [
        migrations.AlterField(
            model_name="information",
            name="map",
            field=models.TextField(blank=True, null=True),
        ),
    ]
