# Generated by Django 4.1.9 on 2023-06-12 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("basic", "0015_alter_information_map"),
    ]

    operations = [
        migrations.AddField(
            model_name="gallery",
            name="category",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="basic.gallerycategory"
            ),
            preserve_default=False,
        ),
    ]
