# Generated by Django 4.1.9 on 2023-06-14 08:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("basic", "0016_gallery_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="subject",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
