# Generated by Django 4.1.9 on 2023-06-14 09:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("basic", "0017_contact_subject"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="information",
            name="more_about",
        ),
        migrations.RemoveField(
            model_name="information",
            name="phone_number",
        ),
        migrations.DeleteModel(
            name="MoreAbout",
        ),
        migrations.DeleteModel(
            name="PhoneNumber",
        ),
        migrations.AddField(
            model_name="information",
            name="phone_number",
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
    ]
