# Generated by Django 4.1.9 on 2023-07-07 04:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("basic", "0018_remove_information_more_about_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="information",
            name="principal_image",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
        migrations.AddField(
            model_name="information",
            name="principal_name",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
