# Generated by Django 4.1.9 on 2023-07-07 05:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("basic", "0019_information_principal_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="information",
            name="principal_message",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
