# Generated by Django 4.1.9 on 2023-07-07 05:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("basic", "0020_information_principal_message"),
    ]

    operations = [
        migrations.CreateModel(
            name="BOD",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100)),
                ("image", models.ImageField(blank=True, upload_to="")),
            ],
        ),
    ]
