# Generated by Django 4.1.9 on 2023-07-07 05:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("basic", "0021_bod"),
    ]

    operations = [
        migrations.AddField(
            model_name="information",
            name="director_image",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
        migrations.AddField(
            model_name="information",
            name="director_message",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="information",
            name="director_name",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
