# Generated by Django 4.1.9 on 2023-07-07 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("basic", "0023_directormessage_principalmessage_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AboutSchool",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("about", models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name="information",
            name="about_school",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="basic.aboutschool"),
        ),
    ]
