# Generated by Django 4.1.9 on 2023-07-07 07:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("basic", "0025_remove_information_about_school_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="information",
            name="mission",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="information",
            name="vision",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
